include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libcc.a
$(libdir)/libcc.a: 1edensity.o 2edensity.o ccd.o ccsd.o ccsdt.o eomeeccsd.o lambdaccsd.o \
                   perturbedccsd.o perturbedlambdaccsd.o
