include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libintegrals.a
$(libdir)/libintegrals.a: 1eints.o 2eints.o center.o \
                          context.o element.o fmgamma.o nai.o \
                          kei.o os.o ovi.o rys.o shell.o \
                          cfour1eints.o cfour2eints.o
