include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libintegrals.a
$(libdir)/libintegrals.a: 1ehamiltonian.o 1eints.o 2eints.o blasx.o center.o cholesky.o \
                          context.o element.o elementdata.o eri.o fmgamma.o \
                          hrr.o ishprim.o kei.o keiprim.o momprim.o nai.o \
                          naiprim.o osinv.o osprim.o ovi.o oviprim.o rys.o shell.o vrr.o
