include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libtensor.a
$(libdir)/libtensor.a: \
dense_tensor.o \
ctf_tensor.o \
spinorbital_tensor.o \
symblocked_tensor.o \
tensor_densify.o \
tensor_mult_dense.o \
tensor_mult.o \
tensor_pack.o \
tensor_print_dense.o \
tensor_print.o \
tensor_scale_dense.o \
tensor_scale.o \
tensor_size_dense.o \
tensor_size.o \
tensor_sum_dense.o \
tensor_sum.o \
tensor_symmetrize.o \
tensor_unpack.o \
tensor_slice_dense.o \
tensor_slice.o \
util.o
