include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libscf.a
$(libdir)/libscf.a: aoints.o aomoints.o aoscf.o cholesky.o choleskymoints.o choleskyscf.o \
                    moints.o scf.o
