include ../../config.mk
include ../make/make.in
include ../make/rules.mk

libs: $(libdir)/libautocc.a
$(libdir)/libautocc.a: diagram.o fraction.o fragment.o generator.o line.o \
                       operator.o term.o
