include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libop.a
$(libdir)/libop.a: 1ehamiltonian.o 2eoperator.o aomoints.o cholesky.o choleskymoints.o \
                   eri.o kei.o moints.o multipole.o nai.o ovi.o perturbedst2eoperator.o \
                   st1eoperator.o st2eoperator.o stexcitationoperator.o
