include ../../config.mk
include ../../rules.mk

libs: $(libdir)/libop.a
$(libdir)/libop.a: 2eoperator.o aomoints.o choleskymoints.o \
                   moints.o perturbedst2eoperator.o \
                   st1eoperator.o st2eoperator.o stexcitationoperator.o
