include ../config.mk
include ../rules.mk

slide_SUBDIRS = slide
scf_SUBDIRS = scf
autocc_SUBDIRS = autocc
time_SUBDIRS = time
input_SUBDIRS = input
aquarius_SUBDIRS = main
cc_SUBDIRS = cc
memory_SUBDIRS = memory
tensor_SUBDIRS = tensor
