
include ../config.mk
include ../rules.mk

libs_SUBDIRS = slide autocc time input memory tensor util cc scf
bins_SUBDIRS = main bench
bench_ao_ccsd_SUBDIRS = bench
bench_ao_ccsd_lambda_SUBDIRS = bench
bench_ao_ccsdt_SUBDIRS = bench
bench_cholesky_ccsd_SUBDIRS = bench
bench_cholesky_ccsd_lambda_SUBDIRS = bench
bench_cholesky_ccsdt_SUBDIRS = bench

.NOTPARALLEL:
